(autoload 'save-current-configuration "revive" "Save status" t)
(autoload 'resume "revive" "Resume Emacs" t)
(autoload 'wipe "revive" "Wipe emacs" t)
(define-key ctl-x-map "R" 'resume)
(define-key ctl-x-map "K" 'wipe)
(add-hook 'kill-emacs-hook 'save-current-configuration)
